# Configuration Scalar Galaxy pour API Fournisseur CG
# Généré automatiquement le 2025-08-03T09:58:30.185Z
# Combine AutoSwagger (routes) + Configuration Scalar (UI/UX)

openapi: 3.0.0
info:
  title: API Fournisseur CG - Orchestrateur Logistique
  version: 3.0.0
  description: >-
    API REST centrale servant de wrapper pour l'écosystème Fournisseur Congo. Orchestrateur entre applications clientes
    (web Vue.js, mobile) et services backend (Appwrite, MailerSend, SMTP, Spark Pay).
  contact:
    name: Équipe Technique Fournisseur CG
    email: dev@fournisseur.cg
    url: https://fournisseur.cg
  license:
    name: Propriétaire - Fournisseur CG
    url: https://fournisseur.cg/license
  termsOfService: https://fournisseur.cg/terms
servers:
  - url: https://api.fournisseur.cg
    description: Production - API officielle
  - url: https://staging.api.fournisseur.cg
    description: Staging - Tests et validation
  - url: http://localhost:3333
    description: Développement local
security:
  - bearerAuth: []
  - apiKeyAuth: []
  - basicAuth: []
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtenu depuis /v3/auth/login
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Clé API pour l'authentification service-à-service
    basicAuth:
      type: http
      scheme: basic
      description: Authentification basique pour les endpoints admin
tags:
  - name: Authentication
    description: Authentification utilisateurs et gestion des tokens JWT
  - name: Database Management
    description: Wrapper pour les opérations Appwrite (collections, documents, utilisateurs)
  - name: Collection Management
    description: Gestion des collections et initialisation des structures de données
  - name: Payment Processing
    description: Intégration Spaark Pay - Paiements mobiles (MTN Money, Airtel Money)
  - name: SMS Notifications
    description: Envoi de SMS et notifications via API SMS
  - name: Email Services
    description: MailerSend (marketing) et SMTP (notifications système)
  - name: User Management
    description: Gestion des utilisateurs (visiteurs, clients, professionnels, admins)
  - name: Webhooks
    description: Endpoints pour webhooks entrants (Spark Pay, partenaires transport)
  - name: Analytics
    description: Métriques, rapports et données analytiques de la plateforme
paths: {}
x-scalar:
  ui:
    theme:
      primaryColor: '#2563eb'
      secondaryColor: '#64748b'
      backgroundColor: '#ffffff'
      textColor: '#1f2937'
    navigation:
      showServers: true
      showSecurity: true
      showExamples: true
      showResponses: true
    examples:
      showRequestExamples: true
      showResponseExamples: true
      defaultLanguage: curl
    documentation:
      showDescription: true
      showContact: true
      showLicense: true
      showTermsOfService: true
  features:
    auth:
      enabled: true
      persistAuthorization: true
      showSecuritySchemes: true
    testing:
      enabled: true
      allowCustomHeaders: true
      allowCustomBody: true
    docs:
      enabled: true
      showCodeSamples: true
      showSchemaExamples: true
    analytics:
      enabled: true
      trackUsage: true
      trackErrors: true
  webhooks:
    enabled: true
    allowCustomWebhooks: true
    defaultTimeout: 30000
  codeSamples:
    languages:
      - curl
      - javascript
      - python
      - php
      - java
      - csharp
    defaultLanguage: curl
    showLineNumbers: true
    showCopyButton: true
  responses:
    showSchema: true
    showExamples: true
    showHeaders: true
    showStatusCodes: true
  search:
    enabled: true
    searchInDescriptions: true
    searchInExamples: true
    searchInSchemas: true
  metadata:
    showVersion: true
    showLastModified: true
    showGeneratedBy: true
    generatedBy: API Fournisseur CG - AutoSwagger + Scalar
    generatedAt: '2025-08-03T09:58:30.184Z'
